x-api-base: &api-base
    container_name: api
    restart: always
    tty: true
    volumes:
        - file-converter-logs:/usr/src/app/logs
    networks:
        - files-converter-network

services:
    api-dev:
        <<: *api-base
        profiles: [dev]
        env_file:
            - ../backend/.env.dev
        build:
            context: ../
            target: development
            dockerfile: ./docker/Dockerfile
        volumes:
            - ../backend:/usr/src/app
            - /usr/src/app/node_modules
            - file-converter-logs:/usr/src/app/logs
            - file-converter-pnpm:/usr/src/app/.pnpm-store
        depends_on:
            - rabbitmq-dev
            - database-dev
            - minio-dev
        command: npm run api:dev

    api-prod:
        <<: *api-base
        profiles: [prod]
        build:
            context: ../
            target: production
            dockerfile: ./docker/Dockerfile
        depends_on:
            - rabbitmq-prod
            - database-prod
            - minio-prod
        command: npm run api:prod
